//fil1=file_text_open_write("globals.txt");
//file_text_write_real(fil1,score2[0]);
//file_text_write_real(fil1,score2[1]);
//file_text_close(fil1);
room_persistent=0;
started=0;
background_delete(background_index[0]);
script_execute(del_fixtures);
room_goto(room0);
